
services:
  app-source-db:
    container_name: etl-example_source-db
    image: postgres
    ports:
      - 5432:5432
    environment:
       - POSTGRES_PASSWORD=dbpassword
       - POSTGRES_USER=dbuser
       - POSTGRES_DB=postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d

