FROM apache/airflow:latest
USER 0
User airflow
RUN pip install numpy \
  && pip install pandas \
  && pip install datetime \
  && pip install airflow-code-editor \
  && pip install apache-airflow-providers-postgres

USER airflow
