
x-common-service-settings:
  &common-service-settings
  networks:
    - etlnetwork

networks:
  etlnetwork:
    name: etl_network

services:
  app-source-db:
    <<: *common-service-settings
    container_name: etl-example_app-source-db
    image: postgres
    ports:
      - 5432:5432
    environment:
       - POSTGRES_PASSWORD=dbpassword
       - POSTGRES_USER=dbuser
       - POSTGRES_DB=postgres
    volumes:
      - ./source-db:/docker-entrypoint-initdb.d

  data-warehouse-db:
    <<: *common-service-settings
    container_name: etl-example_data-warehouse-db
    image: postgres
    ports:
      - 5433:5432
    environment:
       - POSTGRES_PASSWORD=dbpassword
       - POSTGRES_USER=dbuser
       - POSTGRES_DB=postgres
    volumes:
      - ./data-warehouse-db:/docker-entrypoint-initdb.d
